standard = "2019"

[libraries.defaultlib]
files = [
    "src/widget_pkg.vhd",
    "src/widget.vhd",
    "src/counter.vhd",
    "bench/test_utils.vhd",
    "bench/widget_tb.vhd",
    "bench/simple_tb.vhd",
    "bench/broken_tb.vhd",
    "bench/counter_test_tb.vhd",
]

[libraries.quartz]
files = [
    "$HOME/.vw/deps/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/fifos/dcfifo_mixed_xpm.vhd",
    "$HOME/.vw/deps/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/fifos/dcfifo_xpm.vhd",
    "$HOME/.vw/deps/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/fifos/sims/fifos_tb.vhd",
    "$HOME/.vw/deps/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/fifos/sims/fifos_th.vhd",
    "$HOME/.vw/deps/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/fifos/sims/fifos_sim_pkg.vhd",
    "$HOME/.vw/deps/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/axi_blocks/axilite_if_2k19_helper_pkg.vhd",
    "$HOME/.vw/deps/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/axi_blocks/axil_interconnect_2k8.vhd",
    "$HOME/.vw/deps/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/axi_blocks/axilite_if_2k8_pkg.vhd",
    "$HOME/.vw/deps/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/axi_blocks/axist_if_2k19_pkg.vhd",
    "$HOME/.vw/deps/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/axi_blocks/axil_interconnect.vhd",
    "$HOME/.vw/deps/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/axi_blocks/axil_common_pkg.vhd",
    "$HOME/.vw/deps/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/axi_blocks/axil_target_txn.vhd",
    "$HOME/.vw/deps/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/axi_blocks/axilite_if_2k19_pkg.vhd",
    "$HOME/.vw/deps/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/axi_blocks/axil8_resizer.vhd",
    "$HOME/.vw/deps/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/spi_nor_controller/spi_txn/spi_txn_mgr.vhd",
    "$HOME/.vw/deps/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/spi_nor_controller/spi_nor_regs.vhd",
    "$HOME/.vw/deps/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/spi_nor_controller/spi_nor_top.vhd",
    "$HOME/.vw/deps/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/spi_nor_controller/spi_nor_pkg.vhd",
    "$HOME/.vw/deps/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/spi_nor_controller/espi_txn/espi_flash_txn_mgr.vhd",
    "$HOME/.vw/deps/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/spi_nor_controller/sims/spi_nor_th.vhd",
    "$HOME/.vw/deps/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/spi_nor_controller/sims/spi_nor_tb_pkg.vhd",
    "$HOME/.vw/deps/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/spi_nor_controller/sims/spi_nor_tb.vhd",
    "$HOME/.vw/deps/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/spi_nor_controller/link/spi_clk_gen.vhd",
    "$HOME/.vw/deps/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/spi_nor_controller/link/spi_link.vhd",
    "$HOME/.vw/deps/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/spi_nor_controller/mixed_width_adaptor.vhd",
    "$HOME/.vw/deps/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/memories/mixed_width_simple_dpr.vhd",
    "$HOME/.vw/deps/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/memories/sims/memories_th.vhd",
    "$HOME/.vw/deps/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/memories/sims/memories_tb.vhd",
    "$HOME/.vw/deps/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/memories/sims/memories_sim_pkg.vhd",
    "$HOME/.vw/deps/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/memories/dual_clock_simple_dpr.vhd",
    "$HOME/.vw/deps/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/info/info.vhd",
    "$HOME/.vw/deps/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/info/info_2k8.vhd",
    "$HOME/.vw/deps/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/synchronizers/bacd.vhd",
    "$HOME/.vw/deps/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/synchronizers/async_reset_bridge.vhd",
    "$HOME/.vw/deps/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/synchronizers/tacd.vhd",
    "$HOME/.vw/deps/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/synchronizers/sims/synchronizers_th.vhd",
    "$HOME/.vw/deps/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/synchronizers/sims/synchronizers_tb.vhd",
    "$HOME/.vw/deps/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/synchronizers/meta_sync.vhd",
    "$HOME/.vw/deps/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/ignition/target/ignition_status.vhd",
    "$HOME/.vw/deps/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/ignition/target/ignition_io.vhd",
    "$HOME/.vw/deps/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/ignition/target/ignition_target_common.vhd",
    "$HOME/.vw/deps/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/ignition/target/sims/ignition_tgt_sim_tb.vhd",
    "$HOME/.vw/deps/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/ignition/target/sims/ignition_controller_model.vhd",
    "$HOME/.vw/deps/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/ignition/target/sims/ignition_tgt_sim_th.vhd",
    "$HOME/.vw/deps/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/ignition/target/sims/ignition_sim_pkg.vhd",
    "$HOME/.vw/deps/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/ignition/target/ignition_pkg.vhd",
    "$HOME/.vw/deps/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/ignition/target/ibc_control.vhd",
    "$HOME/.vw/deps/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/ignition/target/tx_path/ignition_tx.vhd",
    "$HOME/.vw/deps/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/ignition/target/rx_path/pkt_parsing.vhd",
    "$HOME/.vw/deps/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/ignition/target/rx_path/ignit_rx_pipe.vhd",
    "$HOME/.vw/deps/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/fmc_if/stm32h7_fmc_target_pkg.vhd",
    "$HOME/.vw/deps/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/fmc_if/stm32h7_fmc_target.vhd",
    "$HOME/.vw/deps/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/fmc_if/sims/fmc_tb.vhd",
    "$HOME/.vw/deps/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/fmc_if/sims/fmc_th.vhd",
    "$HOME/.vw/deps/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/fmc_if/sims/fmc_tb_pkg.vhd",
    "$HOME/.vw/deps/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/fmc_if/model/stm32h7_fmc_sim_pkg.vhd",
    "$HOME/.vw/deps/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/fmc_if/model/stm32h7_fmc_model.vhd",
    "$HOME/.vw/deps/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/common/utils/calc_pkg.vhd",
    "$HOME/.vw/deps/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/common/utils/transforms_pkg.vhd",
    "$HOME/.vw/deps/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/common/utils/time_pkg.vhd",
    "$HOME/.vw/deps/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/common/utils/sims/utilities_tb.vhd",
    "$HOME/.vw/deps/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/common/interfaces/tristate_if_pkg.vhd",
    "$HOME/.vw/deps/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/common/countdown/sims/countdown_th.vhd",
    "$HOME/.vw/deps/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/common/countdown/sims/countdown_tb.vhd",
    "$HOME/.vw/deps/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/common/countdown/countdown.vhd",
    "$HOME/.vw/deps/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/common/strobe/sims/strobe_th.vhd",
    "$HOME/.vw/deps/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/common/strobe/sims/strobe_tb.vhd",
    "$HOME/.vw/deps/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/common/strobe/strobe.vhd",
    "$HOME/.vw/deps/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/ls_xcvr/aligner_10bk28_5.vhd",
    "$HOME/.vw/deps/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/ls_xcvr/ls_serdes.vhd",
    "$HOME/.vw/deps/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/8b10b/encode_8b10b.vhd",
    "$HOME/.vw/deps/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/8b10b/decode_8b10b.vhd",
    "$HOME/.vw/deps/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/8b10b/helper_8b10b_pkg.vhd",
    "$HOME/.vw/deps/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/arb_mux_demux/arbiter.vhd",
    "$HOME/.vw/deps/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/arb_mux_demux/arbiter_pkg.vhd",
    "$HOME/.vw/deps/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/arb_mux_demux/sims/arbiter_th.vhd",
    "$HOME/.vw/deps/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/arb_mux_demux/sims/arbiter_sim_pkg.vhd",
    "$HOME/.vw/deps/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/arb_mux_demux/sims/arbiter_tb.vhd",
    "$HOME/.vw/deps/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/espi/espi_spec_regs.vhd",
    "$HOME/.vw/deps/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/espi/flash_channel/flash_channel_pkg.vhd",
    "$HOME/.vw/deps/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/espi/flash_channel/flash_channel.vhd",
    "$HOME/.vw/deps/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/espi/sys_regs/espi_regs.vhd",
    "$HOME/.vw/deps/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/espi/peripheral_channel/uart_channel_pkg.vhd",
    "$HOME/.vw/deps/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/espi/peripheral_channel/uart_channel_top.vhd",
    "$HOME/.vw/deps/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/espi/link_layer/link_layer.vhd",
    "$HOME/.vw/deps/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/espi/link_layer/alert_gen.vhd",
    "$HOME/.vw/deps/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/espi/link_layer/qspi_link_layer_pkg.vhd",
    "$HOME/.vw/deps/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/espi/link_layer/link_layer_pkg.vhd",
    "$HOME/.vw/deps/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/espi/link_layer/dbg_link_faker.vhd",
    "$HOME/.vw/deps/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/espi/link_layer/cmd_sizer.vhd",
    "$HOME/.vw/deps/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/espi/vwire_channel/vwire_block.vhd",
    "$HOME/.vw/deps/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/espi/sims/espi_th.vhd",
    "$HOME/.vw/deps/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/espi/sims/espi_tb_pkg.vhd",
    "$HOME/.vw/deps/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/espi/sims/espi_tb.vhd",
    "$HOME/.vw/deps/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/espi/sims/models/espi_dbg_vc_pkg.vhd",
    "$HOME/.vw/deps/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/espi/sims/models/fake_flash_txn_mgr.vhd",
    "$HOME/.vw/deps/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/espi/sims/models/espi_controller_vc_pkg.vhd",
    "$HOME/.vw/deps/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/espi/txn_layer/response_processor.vhd",
    "$HOME/.vw/deps/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/espi/txn_layer/espi_protocol_pkg.vhd",
    "$HOME/.vw/deps/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/espi/txn_layer/link_to_txn_bridge.vhd",
    "$HOME/.vw/deps/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/espi/txn_layer/txn_layer_top.vhd",
    "$HOME/.vw/deps/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/espi/txn_layer/espi_base_types_pkg.vhd",
    "$HOME/.vw/deps/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/espi/txn_layer/command_processor.vhd",
    "$HOME/.vw/deps/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/espi/espi_target_top.vhd",
    "$HOME/.vw/deps/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/pipeline/skidbuffer.vhd",
    "$HOME/.vw/deps/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/spi/axi_controller/spi_to_axi.vhd",
    "$HOME/.vw/deps/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/spi/axi_controller/spi_axi_controller_top.vhd",
    "$HOME/.vw/deps/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/spi/axi_controller/sims/spi_axi_tb_pkg.vhd",
    "$HOME/.vw/deps/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/spi/axi_controller/sims/spi_axi_tb.vhd",
    "$HOME/.vw/deps/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/spi/axi_controller/sims/spi_axi_th.vhd",
    "$HOME/.vw/deps/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/spi/axi_controller/spi_axi_pkg.vhd",
    "$HOME/.vw/deps/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/spi/spi_target_phy/spi_target_phy.vhd",
    "$HOME/.vw/deps/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/ice40primitives/ice40_pkg.vhd",
    "$HOME/.vw/deps/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/ice40primitives/ice40_lvds_in.vhd",
    "$HOME/.vw/deps/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/crc/crc8atm_8wide.vhd",
    "$HOME/.vw/deps/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/crc/crc_sim_pkg.vhd",
    "$HOME/.vw/deps/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/crc/crc8autostar_8wide.vhd",
    "$HOME/.vw/deps/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/i2c/muxes/oximux16/oximux16_top.vhd",
    "$HOME/.vw/deps/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/i2c/muxes/oximux16/sims/oximux16_tb.vhd",
    "$HOME/.vw/deps/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/i2c/muxes/oximux16/sims/oximux16_th.vhd",
    "$HOME/.vw/deps/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/i2c/muxes/oximux16/sims/oximux16_sim_pkg.vhd",
    "$HOME/.vw/deps/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/i2c/muxes/oximux16/oximux16_function.vhd",
    "$HOME/.vw/deps/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/i2c/muxes/PCA9545ish/pca9545ish_top.vhd",
    "$HOME/.vw/deps/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/i2c/muxes/PCA9545ish/pca9545ish_function.vhd",
    "$HOME/.vw/deps/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/i2c/muxes/PCA9545ish/sims/i2c_pca9545ish_th.vhd",
    "$HOME/.vw/deps/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/i2c/muxes/PCA9545ish/sims/i2c_pca9545ish_sim_pkg.vhd",
    "$HOME/.vw/deps/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/i2c/muxes/PCA9545ish/sims/i2c_pca9545ish_tb.vhd",
    "$HOME/.vw/deps/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/i2c/muxes/PCA9545ish/pca9545_pkg.vhd",
    "$HOME/.vw/deps/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/i2c/common/i2c_common_pkg.vhd",
    "$HOME/.vw/deps/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/i2c/common/i2c_glitch_filter.vhd",
    "$HOME/.vw/deps/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/i2c/target/i2c_base_types_pkg.vhd",
    "$HOME/.vw/deps/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/i2c/target/i2c_target_phy.vhd",
    "$HOME/.vw/deps/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/i2c/target/sims/i2c_target_phy_tb.vhd",
    "$HOME/.vw/deps/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/i2c/target/sims/i2c_target_phy_sim_pkg.vhd",
    "$HOME/.vw/deps/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/i2c/target/sims/i2c_target_phy_th.vhd",
    "$HOME/.vw/deps/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/i2c/target/i2c_phy_consolidator.vhd",
    "$HOME/.vw/deps/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/i2c/io_expanders/PCA9506ish/pca9506_regs.vhd",
    "$HOME/.vw/deps/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/i2c/io_expanders/PCA9506ish/pca9506_pkg.vhd",
    "$HOME/.vw/deps/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/i2c/io_expanders/PCA9506ish/pca9506_function.vhd",
    "$HOME/.vw/deps/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/i2c/io_expanders/PCA9506ish/pca9506_top.vhd",
    "$HOME/.vw/deps/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/i2c/io_expanders/PCA9506ish/sims/i2c_pca9506ish_tb.vhd",
    "$HOME/.vw/deps/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/i2c/io_expanders/PCA9506ish/sims/i2c_pca9506ish_sim_pkg.vhd",
    "$HOME/.vw/deps/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/i2c/io_expanders/PCA9506ish/sims/i2c_pca9506ish_th.vhd",
    "$HOME/.vw/deps/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/i2c/controller/link_layer/i2c_ctrl_link_layer.vhd",
    "$HOME/.vw/deps/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/i2c/controller/i2c_ctrl_top.vhd",
    "$HOME/.vw/deps/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/i2c/controller/txn_layer/sims/i2c_ctrl_txn_layer_th.vhd",
    "$HOME/.vw/deps/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/i2c/controller/txn_layer/sims/i2c_ctrl_txn_layer_tb.vhd",
    "$HOME/.vw/deps/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/i2c/controller/txn_layer/i2c_ctrl_txn_layer.vhd",
    "$HOME/.vw/deps/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/i2c/controller/regs/i2c_ctrl_regs.vhd",
    "$HOME/.vw/deps/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/uart/fifo_uart/axi_fifo_st_uart.vhd",
    "$HOME/.vw/deps/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/uart/sims/uart_th.vhd",
    "$HOME/.vw/deps/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/uart/sims/uart_tb_pkg.vhd",
    "$HOME/.vw/deps/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/uart/sims/uart_tb.vhd",
    "$HOME/.vw/deps/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/uart/base_uart/axi_st_uart.vhd",
    "$HOME/.vw/deps/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/sgpio/sgpio_top.vhd",
    "$HOME/.vw/deps/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/sgpio/sgpio_shift_in.vhd",
    "$HOME/.vw/deps/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/sgpio/sgpio_shift_out.vhd",
    "$HOME/.vw/deps/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/sgpio/sims/sgpio_th.vhd",
    "$HOME/.vw/deps/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/sgpio/sims/sgpio_tb.vhd",
    "$HOME/.vw/deps/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/vunit_components/gpio/sim_gpio.vhd",
    "$HOME/.vw/deps/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/vunit_components/gpio/gpio_msg_pkg.vhd",
    "$HOME/.vw/deps/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/vunit_components/i2c_controller/i2c_ctrlr_vc.vhd",
    "$HOME/.vw/deps/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/vunit_components/i2c_controller/i2c_ctrlr_vc_pkg.vhd",
    "$HOME/.vw/deps/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/vunit_components/spi_controller/spi_pkg.vhd",
    "$HOME/.vw/deps/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/vunit_components/spi_controller/spi_slave.vhd",
    "$HOME/.vw/deps/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/vunit_components/spi_controller/spi_master.vhd",
    "$HOME/.vw/deps/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/vunit_components/i2c_target/i2c_target_vc_pkg.vhd",
    "$HOME/.vw/deps/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/vunit_components/i2c_target/i2c_target_vc.vhd",
    "$HOME/.vw/deps/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/vunit_components/qspi_controller/qspi_controller_vc.vhd",
    "$HOME/.vw/deps/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/vunit_components/qspi_controller/qspi_vc_pkg.vhd",
    "$HOME/.vw/deps/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/vunit_components/I2c_cmd/i2c_cmd_vc.vhd",
    "$HOME/.vw/deps/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/vunit_components/I2c_cmd/i2c_cmd_vc_pkg.vhd",
    "$HOME/.vw/deps/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/vunit_components/sim_gpio.vhd",
    "$HOME/.vw/deps/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/vunit_components/basic_stream/basic_stream_pkg.vhd",
    "$HOME/.vw/deps/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/vunit_components/basic_stream/basic_source.vhd",
    "$HOME/.vw/deps/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/vunit_components/basic_stream/sims/tb_basic_stream.vhd",
    "$HOME/.vw/deps/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/vunit_components/basic_stream/sims/th_basic_stream.vhd",
    "$HOME/.vw/deps/quartz-09a412a5746785ff467040c57328911fb4aeb0ed/vunit_components/basic_stream/basic_sink.vhd",
]
